vich_uploader:
    db_driver: orm
    mappings:
        beginSite_image:
            uri_prefix: '%app.path.site_images%'
            upload_destination: '%kernel.project_dir%/public/images/site'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        finalSite_image:
            uri_prefix: '%app.path.site_images%'
            upload_destination: '%kernel.project_dir%/public/images/site'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
